# Generated by Django 5.2.17 on 2026-08-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='scan_type',
            field=models.CharField(choices=[('port_scan', 'Port Scan'), ('full_port_scan', 'Full Port Scan'), ('udp_scan', 'UDP Scan'), ('service_scan', 'Service Detection'), ('dns_enum', 'DNS Enumeration'), ('subdomain_scan', 'Subdomain Discovery'), ('reverse_dns', 'Reverse DNS Lookup'), ('zone_transfer', 'Zone Transfer Test'), ('dir_buster', 'Directory Brute Force'), ('tech_fingerprint', 'Technology Fingerprint'), ('web_vuln_scan', 'Web Vulnerability Scan'), ('param_fuzzer', 'Parameter Discovery'), ('vuln_scan', 'Vulnerability Scan'), ('ssl_scan', 'SSL/TLS Scan')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduledscan',
            name='scan_type',
            field=models.CharField(choices=[('port_scan', 'Port Scan'), ('full_port_scan', 'Full Port Scan'), ('udp_scan', 'UDP Scan'), ('service_scan', 'Service Detection'), ('dns_enum', 'DNS Enumeration'), ('subdomain_scan', 'Subdomain Discovery'), ('reverse_dns', 'Reverse DNS Lookup'), ('zone_transfer', 'Zone Transfer Test'), ('dir_buster', 'Directory Brute Force'), ('tech_fingerprint', 'Technology Fingerprint'), ('web_vuln_scan', 'Web Vulnerability Scan'), ('param_fuzzer', 'Parameter Discovery'), ('vuln_scan', 'Vulnerability Scan'), ('ssl_scan', 'SSL/TLS Scan')], max_length=50),
        ),
    ]
